spring.application.name=tutoria_pei_fran

spring.datasource.url=jdbc:sqlite:${DATABASE_PATH:./data/tutoria.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.address=0.0.0.0
server.port=8080
server.ssl.enabled=false

#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=TutoriaPEIFRAN
#server.ssl.key-alias=springboot

#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#logging.level.org.hibernate=DEBUG